import { PDFDocument, rgb, StandardFonts, type PDFFont } from "pdf-lib";
import type { PaymentRecord } from "../reports/record.js";

/** One line of the record: a label and its values. The dashboard page and the PDF are both drawn from this list. */
export interface RecordLine {
  label: string;
  values: { text: string; mono?: boolean; note?: boolean; strong?: boolean }[];
}

export function recordLines(r: PaymentRecord): RecordLine[] {
  const lines: RecordLine[] = [
    { label: "Paid by", values: [{ text: r.org }, { text: r.account, mono: true }] },
    { label: "Paid to", values: [{ text: r.recipient }, ...(r.address ? [{ text: r.address, mono: true }] : []), ...(r.email ? [{ text: r.email }] : [])] },
    { label: "Amount", values: [{ text: `${r.amount} ${r.token}`, strong: true }] },
    { label: "Value in USD", values: [{ text: `${r.usdValue} USD` }, { text: r.priceSource, note: true }] },
    { label: "Date", values: [{ text: r.executedAt ?? "—" }] },
    { label: "Category", values: [{ text: r.category ?? "—" }] },
    { label: "Payout", values: [{ text: r.payout }] },
    { label: "Requested by", values: [{ text: r.requestedBy ?? "not recorded" }, ...(r.requestedAt ? [{ text: r.requestedAt, note: true }] : [])] },
    {
      label: "Approved by",
      values: [
        ...(r.approvedBy.length ? r.approvedBy.map((a) => ({ text: `${a.who} · ${a.at}` })) : [{ text: "not recorded" }]),
        { text: `${r.threshold} approvals required`, note: true },
      ],
    },
    { label: "How it reached the recipient", values: r.delivery.map((text) => ({ text })) },
    { label: "Network", values: [{ text: r.network }] },
    { label: "Transaction", values: [{ text: r.txHash ?? "—", mono: true }] },
  ];
  if (r.settleTx) lines.push({ label: `${r.status.startsWith("Returned") ? "Return" : "Claim"} transaction`, values: [{ text: r.settleTx, mono: true }] });
  return lines;
}

export const recordTitle = (r: PaymentRecord) => `${r.amount} ${r.token} to ${r.recipient}`;
export const recordFooter = (r: PaymentRecord, generatedAt: string) =>
  `This is a record of a payment from the organization's account, generated by Omniflow on ${generatedAt}. It is not a tax form and not tax advice. Record ${r.payoutId} / ${r.rowId}.`;

const A4: [number, number] = [595.28, 841.89];
const M = 56;

/** The standard fonts speak WinAnsi only: anything they cannot draw becomes "?" instead of failing the whole file. */
function drawable(font: PDFFont, s: string) {
  let out = "";
  for (const ch of s) {
    try {
      font.encodeText(ch);
      out += ch;
    } catch {
      out += "?";
    }
  }
  return out;
}

function wrap(font: PDFFont, size: number, text: string, width: number): string[] {
  const out: string[] = [];
  for (const para of text.split("\n")) {
    let line = "";
    for (const word of para.split(" ")) {
      const next = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(next, size) <= width) {
        line = next;
        continue;
      }
      if (line) out.push(line);
      // a word wider than the column (an address, a hash) is broken by characters
      let w = word;
      while (font.widthOfTextAtSize(w, size) > width) {
        let n = w.length;
        while (n > 1 && font.widthOfTextAtSize(w.slice(0, n), size) > width) n--;
        out.push(w.slice(0, n));
        w = w.slice(n);
      }
      line = w;
    }
    out.push(line);
  }
  return out;
}

/** The payment record as a one-page A4 PDF, built in code (no HTML printing). */
export async function recordPdf(r: PaymentRecord, generatedAt: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(`Payment record — ${r.recipient}`);
  doc.setProducer("Omniflow");
  doc.setCreator("Omniflow");
  const page = doc.addPage(A4);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const mono = await doc.embedFont(StandardFonts.Courier);
  const ink = rgb(0.07, 0.09, 0.15);
  const grey = rgb(0.42, 0.45, 0.5);
  const rule = rgb(0.9, 0.91, 0.93);
  const [W, H] = A4;
  let y = H - M;

  page.drawText("OMNIFLOW", { x: M, y, size: 9, font: bold, color: rgb(0.23, 0.34, 0.91) });
  const kind = "PAYMENT RECORD";
  page.drawText(kind, { x: W - M - font.widthOfTextAtSize(kind, 9), y, size: 9, font, color: grey });
  y -= 30;
  for (const l of wrap(bold, 18, drawable(bold, recordTitle(r)), W - 2 * M)) {
    page.drawText(l, { x: M, y, size: 18, font: bold, color: ink });
    y -= 22;
  }
  page.drawText(drawable(font, `${r.status} · ${r.executedAt ?? ""}`), { x: M, y, size: 10, font, color: grey });
  y -= 20;

  const labelW = 150;
  const valueX = M + labelW + 12;
  const valueW = W - M - valueX;
  for (const line of recordLines(r)) {
    page.drawLine({ start: { x: M, y: y + 4 }, end: { x: W - M, y: y + 4 }, thickness: 0.6, color: rule });
    y -= 12;
    const top = y;
    let ly = top;
    for (const l of wrap(bold, 9.5, drawable(bold, line.label), labelW)) {
      page.drawText(l, { x: M, y: ly, size: 9.5, font: bold, color: rgb(0.29, 0.33, 0.39) });
      ly -= 12;
    }
    let vy = top;
    for (const v of line.values) {
      const f = v.mono ? mono : v.strong ? bold : font;
      const size = v.mono ? 8.5 : v.note ? 8.5 : 10;
      for (const l of wrap(f, size, drawable(f, v.text), valueW)) {
        page.drawText(l, { x: valueX, y: vy, size, font: f, color: v.note ? grey : ink });
        vy -= size + 3.5;
      }
    }
    y = Math.min(ly, vy) - 6;
  }
  page.drawLine({ start: { x: M, y: y + 4 }, end: { x: W - M, y: y + 4 }, thickness: 0.6, color: rule });
  y -= 18;
  for (const l of wrap(font, 8, drawable(font, recordFooter(r, generatedAt)), W - 2 * M)) {
    page.drawText(l, { x: M, y, size: 8, font, color: grey });
    y -= 11;
  }
  return doc.save();
}
