import { createHash, randomBytes } from "node:crypto";
import { formatUnits } from "viem";
import type { Db } from "../db/db.js";
import type { Mailer } from "../mail/mailer.js";
import { HttpError } from "../payouts/service.js";
import type { PriceSource } from "../reports/service.js";
import { documentLabel, irsFile, isRecipientForm, NEC, RECIPIENT_FORMS, type RecipientForm } from "./irs.js";
import { fill1099Nec, normalizeTin, type Party } from "./nec.js";

const sha256 = (b: Uint8Array | string) => createHash("sha256").update(b).digest("hex");
const EMAIL = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
const MAX_UPLOAD = 8 * 1024 * 1024;
const day = (d: Date | string | null) => (d ? new Date(d).toISOString().slice(0, 10) : null);

export interface RowDocuments {
  required: RecipientForm | "none";
  status: "none" | "requested" | "received";
  label: string;
  receivedAt: string | null;
  requestedAt: string | null;
  hash: string | null;
  /** where received forms go (an email address), or null when the organization has not set it */
  destination: string | null;
  /** whether a form can be requested now, and why not */
  canRequest: { ok: boolean; reason?: string };
}

/**
 * Documents around a payment. Two kinds that never mix:
 * - generated by Omniflow from payment data it already has: the payment record, the year-end 1099-NEC (Copy B);
 * - given by the recipient: W-9, W-8BEN, W-8BEN-E — official IRS blanks, signed by the recipient.
 * A received form is passed on to the payer by email; Omniflow keeps its type, the date and the SHA-256, never the file.
 * Nothing here blocks a payment, fills a recipient's form, files anything with the IRS, or suggests which form applies.
 */
export class DocumentService {
  constructor(
    private readonly db: Db,
    private readonly mailer: Mailer,
    private readonly price: PriceSource,
    private readonly decimals: number,
    private readonly formBaseUrl: string,
  ) {}

  private async row(payoutId: string, rowKey: string) {
    const { rows } = await this.db.query(
      `SELECT r.*, p.org_id, o.name AS org_name, o.doc_destination,
              (SELECT max(d.created_at) FROM doc_requests d WHERE d.row_id=r.id) AS requested_at
         FROM payout_rows r JOIN payouts p ON p.id=r.payout_id JOIN orgs o ON o.id=p.org_id
        WHERE r.payout_id=$1 AND r.row_key=$2`,
      [payoutId, rowKey],
    );
    if (!rows[0]) throw new HttpError(404, "row not found");
    return rows[0];
  }

  async documents(payoutId: string, rowKey: string): Promise<RowDocuments> {
    const r = await this.row(payoutId, rowKey);
    const canRequest = !r.email
      ? { ok: false, reason: "The request goes by email, and this recipient has no email address." }
      : !r.doc_destination
        ? { ok: false, reason: "Set where to put received forms in Settings first." }
        : { ok: true };
    return {
      required: r.doc_required,
      status: r.doc_status,
      label: documentLabel(r.doc_required, r.doc_status),
      receivedAt: day(r.doc_received_at),
      requestedAt: day(r.requested_at),
      hash: r.doc_hash,
      destination: r.doc_destination,
      canRequest,
    };
  }

  /** Asks the recipient, by email, for one of the forms. The recipient decides which one applies to them. */
  async request(payoutId: string, rowKey: string, type: unknown, actor: string) {
    if (!isRecipientForm(type)) throw new HttpError(400, "choose W-9, W-8BEN or W-8BEN-E");
    const r = await this.row(payoutId, rowKey);
    const can = (await this.documents(payoutId, rowKey)).canRequest;
    if (!can.ok) throw new HttpError(409, can.reason!);
    const token = randomBytes(24).toString("base64url");
    await this.db.query(`INSERT INTO doc_requests (row_id, token_hash, expires_at) VALUES ($1,$2, now() + interval '60 days')`, [r.id, sha256(token)]);
    await this.db.query(`UPDATE payout_rows SET doc_required=$2, doc_status='requested', doc_received_at=NULL, doc_hash=NULL WHERE id=$1`, [r.id, type]);
    const link = `${this.formBaseUrl}#/tax-form/${token}`;
    await this.mailer.send({
      to: r.email,
      fromName: `${r.org_name} via Omniflow`,
      subject: `${r.org_name} needs a tax form from you`,
      text: `${r.org_name} needs a tax form from you before your payment can be reported.\n\nOpen this link, pick the form that applies to you, download the official IRS blank, sign it and upload it:\n${link}\n\nOmniflow does not fill the form for you and does not check it. The file goes to ${r.org_name}; Omniflow keeps only its type, the date and a fingerprint.`,
    });
    await this.audit(r.org_id, actor, "document.requested", { payoutId, row: rowKey, form: RECIPIENT_FORMS[type].label });
    return this.documents(payoutId, rowKey);
  }

  private async byToken(token: string) {
    const { rows } = await this.db.query(
      `SELECT d.id AS request_id, d.expires_at, r.id AS row_id, r.row_key, r.payout_id, r.name, r.doc_status, r.doc_required, r.doc_received_at,
              p.org_id, o.name AS org_name, o.doc_destination
         FROM doc_requests d JOIN payout_rows r ON r.id=d.row_id JOIN payouts p ON p.id=r.payout_id JOIN orgs o ON o.id=p.org_id
        WHERE d.token_hash=$1`,
      [sha256(token)],
    );
    const d = rows[0];
    if (!d || new Date(d.expires_at) < new Date()) throw new HttpError(404, "link not found or expired");
    return d;
  }

  /** Public view of a form request: who asks, and the blanks on offer. No hint which form to pick. */
  async view(token: string) {
    const d = await this.byToken(token);
    return {
      org: d.org_name,
      name: d.name,
      received: d.doc_status === "received" ? { form: documentLabel(d.doc_required, d.doc_status), at: day(d.doc_received_at) } : null,
      forms: (Object.keys(RECIPIENT_FORMS) as RecipientForm[]).map((k) => ({ type: k, label: RECIPIENT_FORMS[k].label, revision: RECIPIENT_FORMS[k].revision })),
    };
  }

  /** The signed form: passed on to the payer by email; here only type, date and SHA-256 remain. */
  async upload(token: string, input: { type?: unknown; filename?: string; contentBase64?: string }) {
    const d = await this.byToken(token);
    if (!isRecipientForm(input.type)) throw new HttpError(400, "choose which form you are sending");
    if (!d.doc_destination) throw new HttpError(409, `${d.org_name} has not set where to receive forms yet — try again later`);
    const content = Buffer.from(input.contentBase64 ?? "", "base64");
    if (!content.length) throw new HttpError(400, "the file is empty");
    if (content.length > MAX_UPLOAD) throw new HttpError(413, "the file is larger than 8 MB");
    if (content.subarray(0, 5).toString("latin1") !== "%PDF-") throw new HttpError(400, "upload the signed form as a PDF file");
    const hash = sha256(content);
    const label = RECIPIENT_FORMS[input.type].label;
    await this.mailer.send({
      to: d.doc_destination,
      fromName: "Omniflow",
      subject: `${label} from ${d.name}`,
      text: `${d.name} sent a signed ${label} for a payment from ${d.org_name}. The file is attached.\n\nSHA-256: ${hash}\n\nOmniflow did not check the form and does not keep the file — only its type, the date and this fingerprint.`,
      attachments: [{ filename: `${label}-${d.name}.pdf`.replace(/[^\w.-]+/g, "-"), contentType: "application/pdf", content }],
    });
    await this.db.query(`UPDATE payout_rows SET doc_required=$2, doc_status='received', doc_received_at=now(), doc_hash=$3 WHERE id=$1`, [d.row_id, input.type, hash]);
    await this.db.query(`UPDATE doc_requests SET fulfilled_at=now() WHERE id=$1`, [d.request_id]);
    await this.audit(d.org_id, null, "document.received", { payoutId: d.payout_id, row: d.row_key, form: label, sha256: hash });
    return { form: label, receivedAt: day(new Date()), sha256: hash };
  }

  /** The official blank, byte for byte. */
  blank(type: string) {
    if (!isRecipientForm(type)) throw new HttpError(404, "unknown form");
    const f = RECIPIENT_FORMS[type];
    return { bytes: irsFile(f.file), filename: f.file, revision: f.revision };
  }

  // ------------------------------------------------------------------ year-end 1099-NEC

  /** Recipients with a W-9 on file and what they were paid in the year (USD), from payment data. */
  async yearEnd(orgId: string, year: number) {
    const { rows } = await this.db.query(
      `SELECT r.*, o.token, coalesce(lower(r.email), lower(r.address), 'name:' || lower(r.name)) AS rkey
         FROM payout_rows r JOIN payouts p ON p.id=r.payout_id JOIN orgs o ON o.id=p.org_id WHERE p.org_id=$1`,
      [orgId],
    );
    const by = new Map<string, { key: string; name: string; email: string | null; address: string | null; w9: boolean; usd: number; payments: number }>();
    for (const r of rows) {
      const e = by.get(r.rkey) ?? { key: r.rkey, name: r.name, email: r.email, address: r.address, w9: false, usd: 0, payments: 0 };
      if (r.doc_required === "w9" && r.doc_status === "received") e.w9 = true;
      // paid in the year: delivered to the recipient (direct transfer or claimed link)
      if (["sent", "claimed"].includes(r.status) && r.executed_at && new Date(r.executed_at).getUTCFullYear() === year) {
        const { price } = await this.price.usdPrice(r.token, r.executed_at);
        e.usd += Number(formatUnits(BigInt(r.amount), this.decimals)) * price;
        e.payments++;
      }
      by.set(r.rkey, e);
    }
    const years = [...new Set(rows.filter((r) => r.executed_at).map((r) => new Date(r.executed_at).getUTCFullYear()))].sort().reverse();
    return {
      year,
      years: years.length ? years : [new Date().getUTCFullYear()],
      form: { name: "1099-NEC", revision: NEC.revision, copy: "Copy B — For Recipient", firstYear: NEC.firstYear },
      recipients: [...by.values()].filter((e) => e.w9).map((e) => ({ ...e, usd: e.usd.toFixed(2) })),
    };
  }

  /** One filled 1099-NEC, Copy B, for one recipient with a W-9 on file. TINs and addresses come in, are drawn, and are not kept. */
  async nec(orgId: string, actor: string, input: { year: number; recipient: string; payer: Party; recipientInfo: Omit<Party, "name"> }) {
    const year = Number(input.year);
    if (!Number.isInteger(year) || year < NEC.firstYear) throw new HttpError(400, `Form 1099-NEC Rev. ${NEC.revision} is for ${NEC.firstYear} and later`);
    const y = await this.yearEnd(orgId, year);
    const r = y.recipients.find((x) => x.key === input.recipient);
    if (!r) throw new HttpError(404, "no W-9 on file for this recipient");
    const payerTin = normalizeTin(input.payer?.tin ?? "");
    const recipientTin = normalizeTin(input.recipientInfo?.tin ?? "");
    if (!input.payer?.name?.trim()) throw new HttpError(400, "the payer's legal name is required");
    if (!payerTin) throw new HttpError(400, "the payer's TIN must have 9 digits (EIN 12-3456789)");
    if (!recipientTin) throw new HttpError(400, `${r.name}'s TIN must have 9 digits (SSN 123-45-6789 or EIN 12-3456789), as on their W-9`);
    const bytes = await fill1099Nec({
      year,
      payer: { ...input.payer, name: input.payer.name.trim(), tin: payerTin },
      recipient: { ...input.recipientInfo, name: r.name, tin: recipientTin },
      nonemployeeCompensation: r.usd,
    });
    await this.audit(orgId, actor, "document.1099nec", { year, recipient: r.name, box1: r.usd });
    const slug = r.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "recipient";
    return { bytes, filename: `1099-nec-${slug}-${year}.pdf` };
  }

  private async audit(orgId: string, actor: string | null, action: string, details: unknown) {
    await this.db.query(`INSERT INTO audit_log (org_id, actor, action, details) VALUES ($1,$2,$3,$4)`, [orgId, actor, action, JSON.stringify(details)]);
  }
}
